# Advanced Problems with Solutions: Complex Numbers in Python

This notebook contains advanced practice problems on Python complex numbers, including arithmetic, conjugates, floating-point precision, `cmath`, polar/rectangular conversions, roots, sorting strategies, and numerical stability.

## Problem 1: Stable equality for complex numbers

Python compares complex numbers using exact equality on their floating-point real and imaginary parts. Write a function `complex_isclose(z1, z2, rel_tol=1e-9, abs_tol=0.0)` that returns whether two complex numbers are close.

Then test it on:

```python
0.1j + 0.1j + 0.1j
0.3j
```

In [1]:
import cmath

def complex_isclose(z1, z2, rel_tol=1e-9, abs_tol=0.0):
    return cmath.isclose(z1, z2, rel_tol=rel_tol, abs_tol=abs_tol)

z1 = 0.1j + 0.1j + 0.1j
z2 = 0.3j

print(z1 == z2)
print(complex_isclose(z1, z2))

False
True


### Solution explanation

`z1 == z2` is `False` because `0.1` cannot be represented exactly in binary floating-point form. `cmath.isclose` compares the magnitudes of the difference using tolerance-based logic, making it appropriate for numerical complex comparisons.

## Problem 2: Manual complex division

For two complex numbers:

```python
z = 7 - 3j
w = 2 + 5j
```

Compute `z / w` manually using the conjugate formula:

$$
\frac{z}{w} = \frac{z\overline{w}}{w\overline{w}}
$$

Verify that your result matches Python's built-in division.

In [2]:
z = 7 - 3j
w = 2 + 5j

manual = z * w.conjugate() / (w * w.conjugate())
builtin = z / w

print(manual)
print(builtin)
print(cmath.isclose(manual, builtin))

(-0.034482758620689655-1.4137931034482758j)
(-0.03448275862068961-1.4137931034482758j)
True


### Solution explanation

Multiplying numerator and denominator by the conjugate of the denominator removes the imaginary part from the denominator. Since `w * w.conjugate()` equals `abs(w) ** 2`, the denominator becomes a real number.

## Problem 3: Sort complex numbers meaningfully

Python does not define `<`, `<=`, `>`, or `>=` for complex numbers.

Given the list below, sort it in two ways:

1. By magnitude.
2. By phase angle.

```python
numbers = [3 + 4j, -1 + 1j, 2 - 2j, -5 + 0j, 1j, 1 + 0j]
```

In [3]:
numbers = [3 + 4j, -1 + 1j, 2 - 2j, -5 + 0j, 1j, 1 + 0j]

by_magnitude = sorted(numbers, key=abs)
by_phase = sorted(numbers, key=cmath.phase)

print("Sorted by magnitude:")
print(by_magnitude)

print("\nSorted by phase:")
print(by_phase)

Sorted by magnitude:
[1j, (1+0j), (-1+1j), (2-2j), (3+4j), (-5+0j)]

Sorted by phase:
[(2-2j), (1+0j), (3+4j), 1j, (-1+1j), (-5+0j)]


### Solution explanation

Complex numbers are not naturally ordered because there is no single universally accepted ordering compatible with complex arithmetic. However, Python can sort them using a `key`, such as `abs(z)` for magnitude or `cmath.phase(z)` for angle.

## Problem 4: Convert rectangular form to polar form and back

Write two functions:

```python
to_polar(z)
from_polar(r, theta)
```

`to_polar(z)` should return `(r, theta)`.

`from_polar(r, theta)` should reconstruct the complex number.

Test your functions on:

```python
z = -3 + 3j
```

In [4]:
def to_polar(z):
    return abs(z), cmath.phase(z)

def from_polar(r, theta):
    return cmath.rect(r, theta)

z = -3 + 3j
r, theta = to_polar(z)
reconstructed = from_polar(r, theta)

print("r =", r)
print("theta =", theta)
print("reconstructed =", reconstructed)
print("close?", cmath.isclose(z, reconstructed))

r = 4.242640687119285
theta = 2.356194490192345
reconstructed = (-2.9999999999999996+3j)
close? True


### Solution explanation

`abs(z)` gives the magnitude of the complex number, while `cmath.phase(z)` gives the angle in radians. `cmath.rect(r, theta)` converts polar coordinates back to rectangular form.

## Problem 5: Compute all nth roots of a complex number

Write a function `nth_roots(z, n)` that returns all `n` complex roots of `z`.

Use the formula:

$$
z_k = r^{1/n} e^{i(\theta + 2\pi k)/n}, \quad k = 0, 1, ..., n-1
$$

Find all cube roots of:

```python
z = 8
```

In [5]:
def nth_roots(z, n):
    if n <= 0:
        raise ValueError("n must be a positive integer")
        
    r = abs(z)
    theta = cmath.phase(z)
    root_magnitude = r ** (1 / n)
    
    return [
        cmath.rect(root_magnitude, (theta + 2 * cmath.pi * k) / n)
        for k in range(n)
    ]

roots = nth_roots(8, 3)

for root in roots:
    print(root, "->", root ** 3)

(2+0j) -> (8+0j)
(-0.9999999999999996+1.7320508075688774j) -> (7.999999999999998-4.884981308350689e-15j)
(-1.0000000000000009-1.732050807568877j) -> (8.000000000000002-1.1546319456101628e-14j)


### Solution explanation

A nonzero complex number has exactly `n` distinct nth roots. They are evenly spaced around a circle in the complex plane. For `z = 8`, the cube roots include `2`, plus two non-real complex roots.

## Problem 6: Use Euler's formula to generate points on the unit circle

Generate 12 equally spaced complex numbers on the unit circle using:

$$
z_k = e^{2\pi i k / 12}
$$

Verify that every point has magnitude close to `1`.

In [6]:
points = [cmath.exp(2j * cmath.pi * k / 12) for k in range(12)]

for k, z in enumerate(points):
    print(k, z, abs(z), cmath.isclose(abs(z), 1.0))

0 (1+0j) 1.0 True
1 (0.8660254037844387+0.49999999999999994j) 1.0 True
2 (0.5000000000000001+0.8660254037844386j) 1.0 True
3 (6.123233995736766e-17+1j) 1.0 True
4 (-0.4999999999999998+0.8660254037844387j) 0.9999999999999999 True
5 (-0.8660254037844387+0.49999999999999994j) 1.0 True
6 (-1+1.2246467991473532e-16j) 1.0 True
7 (-0.8660254037844388-0.4999999999999997j) 1.0 True
8 (-0.5000000000000004-0.8660254037844385j) 1.0 True
9 (-1.8369701987210297e-16-1j) 1.0 True
10 (0.5000000000000001-0.8660254037844386j) 1.0 True
11 (0.8660254037844384-0.5000000000000004j) 1.0 True


### Solution explanation

Euler's formula says `exp(iθ) = cos(θ) + i sin(θ)`. Therefore, every number generated this way lies on the unit circle, up to small floating-point error.

## Problem 7: Avoid using `math` on complex values

Write a function `safe_sqrt(x)` that returns:

- `math.sqrt(x)` when `x` is a nonnegative real number.
- `cmath.sqrt(x)` when `x` is complex or negative.

Test it with:

```python
25
-25
3 + 4j
```

In [7]:
import math

def safe_sqrt(x):
    if isinstance(x, complex):
        return cmath.sqrt(x)
    if x < 0:
        return cmath.sqrt(x)
    return math.sqrt(x)

tests = [25, -25, 3 + 4j]

for value in tests:
    print(value, "->", safe_sqrt(value))

25 -> 5.0
-25 -> 5j
(3+4j) -> (2+1j)


### Solution explanation

`math.sqrt` only supports real-valued inputs that produce real-valued outputs. `cmath.sqrt` supports complex-valued outputs, so it is appropriate for negative or complex inputs.

## Problem 8: Solve a quadratic equation with complex roots

Write a function `quadratic_roots(a, b, c)` that solves:

$$
ax^2 + bx + c = 0
$$

The function should work even when the discriminant is negative.

Test it on:

```python
x^2 + 2x + 5 = 0
```

In [8]:
def quadratic_roots(a, b, c):
    if a == 0:
        raise ValueError("a must be nonzero")
        
    discriminant = b ** 2 - 4 * a * c
    sqrt_disc = cmath.sqrt(discriminant)
    
    return (
        (-b + sqrt_disc) / (2 * a),
        (-b - sqrt_disc) / (2 * a)
    )

roots = quadratic_roots(1, 2, 5)
print(roots)

for x in roots:
    print(x, "->", x ** 2 + 2 * x + 5)

((-1+2j), (-1-2j))
(-1+2j) -> 0j
(-1-2j) -> 0j


### Solution explanation

The discriminant is `2 ** 2 - 4 * 1 * 5 = -16`. Since the square root of a negative number is complex, `cmath.sqrt` is required. The two roots are `-1 + 2j` and `-1 - 2j`.

## Problem 9: Implement complex normalization

Write a function `normalize_complex(z)` that returns a complex number with the same direction as `z`, but magnitude `1`.

If `z == 0`, raise a `ValueError`.

Test it on:

```python
3 + 4j
-2 - 2j
0j
```

In [9]:
def normalize_complex(z):
    magnitude = abs(z)
    if magnitude == 0:
        raise ValueError("Cannot normalize zero")
    return z / magnitude

for z in [3 + 4j, -2 - 2j]:
    normalized = normalize_complex(z)
    print(z, "->", normalized, "magnitude:", abs(normalized))

try:
    normalize_complex(0j)
except ValueError as error:
    print("Error:", error)

(3+4j) -> (0.6+0.8j) magnitude: 1.0
(-2-2j) -> (-0.7071067811865475-0.7071067811865475j) magnitude: 0.9999999999999999
Error: Cannot normalize zero


### Solution explanation

Dividing a nonzero complex number by its magnitude places it on the unit circle while preserving its angle. Zero has no direction, so it cannot be normalized.

## Problem 10: Detect whether complex numbers lie on a circle

Write a function `on_circle(z, center, radius, tol=1e-9)` that checks whether `z` lies on the circle with a given complex center and real radius.

A point `z` lies on the circle if:

$$
|z - center| = radius
$$

Test it with center `2 + 3j`, radius `5`, and the following points:

```python
7 + 3j
2 + 8j
2 + 7.999999999j
1 + 1j
```

In [10]:
def on_circle(z, center, radius, tol=1e-9):
    return math.isclose(abs(z - center), radius, abs_tol=tol)

center = 2 + 3j
radius = 5
points = [7 + 3j, 2 + 8j, 2 + 7.999999999j, 1 + 1j]

for point in points:
    print(point, "->", on_circle(point, center, radius))

(7+3j) -> True
(2+8j) -> True
(2+7.999999999j) -> True
(1+1j) -> False


### Solution explanation

The expression `abs(z - center)` computes the Euclidean distance between the point and the center. Because floating-point values may contain small errors, `math.isclose` is better than direct equality.

## Problem 11: Rotate complex points around the origin

A complex number can represent a point in the plane. Multiplying by `exp(iθ)` rotates the point by angle `θ` around the origin.

Write a function `rotate(z, theta)` and rotate `1 + 0j` by 90, 180, and 270 degrees.

In [11]:
def rotate(z, theta):
    return z * cmath.exp(1j * theta)

z = 1 + 0j
angles_degrees = [90, 180, 270]

for degrees in angles_degrees:
    theta = math.radians(degrees)
    result = rotate(z, theta)
    print(degrees, "degrees:", result)

90 degrees: (6.123233995736766e-17+1j)
180 degrees: (-1+1.2246467991473532e-16j)
270 degrees: (-1.8369701987210297e-16-1j)


### Solution explanation

Multiplication by `exp(iθ)` changes the phase of a complex number by `θ` while preserving its magnitude. Small real or imaginary residues such as `6.123233995736766e-17` are floating-point artifacts and should be treated as approximately zero.

## Problem 12: Clean tiny numerical artifacts

Rotations and trigonometric computations often produce tiny floating-point artifacts.

Write a function `clean_complex(z, tol=1e-12)` that replaces very small real or imaginary parts with `0.0`.

Test it on the outputs from rotating `1 + 0j` by 90, 180, and 270 degrees.

In [12]:
def clean_complex(z, tol=1e-12):
    real = 0.0 if abs(z.real) < tol else z.real
    imag = 0.0 if abs(z.imag) < tol else z.imag
    return complex(real, imag)

for degrees in [90, 180, 270]:
    theta = math.radians(degrees)
    raw = rotate(1 + 0j, theta)
    cleaned = clean_complex(raw)
    print(degrees, "raw:", raw, "cleaned:", cleaned)

90 raw: (6.123233995736766e-17+1j) cleaned: 1j
180 raw: (-1+1.2246467991473532e-16j) cleaned: (-1+0j)
270 raw: (-1.8369701987210297e-16-1j) cleaned: -1j


### Solution explanation

Floating-point arithmetic often produces values extremely close to zero instead of exact zero. Cleaning is useful for display, but the original values should usually be preserved for serious numerical computation.

## Problem 13: Find roots of unity

The `n`th roots of unity are the solutions to:

$$
z^n = 1
$$

Use your `nth_roots` function to compute the 8th roots of unity. Verify that each root satisfies `z ** 8 ≈ 1`.

In [13]:
roots_8 = nth_roots(1, 8)

for root in roots_8:
    print(clean_complex(root), "->", cmath.isclose(root ** 8, 1, abs_tol=1e-9))

(1+0j) -> True
(0.7071067811865476+0.7071067811865476j) -> True
1j -> True
(-0.7071067811865475+0.7071067811865476j) -> True
(-1+0j) -> True
(-0.7071067811865477-0.7071067811865475j) -> True
-1j -> True
(0.7071067811865474-0.7071067811865477j) -> True


### Solution explanation

The roots of unity are evenly spaced around the unit circle. For `n = 8`, the angle between neighboring roots is `2π / 8 = π / 4` radians.

## Problem 14: Compare `cmath.sqrt(z) ** 2` with `z`

For each value below, compute `cmath.sqrt(z) ** 2` and compare it to `z` using exact equality and `cmath.isclose`.

```python
values = [1 + 5j, -4 + 0j, -3 - 7j, 0.1 + 0.2j]
```

In [14]:
values = [1 + 5j, -4 + 0j, -3 - 7j, 0.1 + 0.2j]

for z in values:
    result = cmath.sqrt(z) ** 2
    print("z:", z)
    print("sqrt(z) ** 2:", result)
    print("exact equality:", result == z)
    print("isclose:", cmath.isclose(result, z, abs_tol=1e-12))
    print()

z: (1+5j)
sqrt(z) ** 2: (0.9999999999999996+5j)
exact equality: False
isclose: True

z: (-4+0j)
sqrt(z) ** 2: (-4+0j)
exact equality: True
isclose: True

z: (-3-7j)
sqrt(z) ** 2: (-3.000000000000001-7j)
exact equality: False
isclose: True

z: (0.1+0.2j)
sqrt(z) ** 2: (0.10000000000000006+0.2j)
exact equality: False
isclose: True



### Solution explanation

Mathematically, squaring a square root should return the original value. Numerically, tiny floating-point errors can appear, especially in the real or imaginary component. Tolerance-based comparison is safer.

## Problem 15: Build a mini complex-number analyzer

Write a function `analyze_complex(z)` that returns a dictionary containing:

- `real`
- `imag`
- `conjugate`
- `magnitude`
- `phase`
- `unit_direction`

For `z = 0`, set `unit_direction` to `None`.

In [15]:
def analyze_complex(z):
    magnitude = abs(z)
    return {
        "real": z.real,
        "imag": z.imag,
        "conjugate": z.conjugate(),
        "magnitude": magnitude,
        "phase": cmath.phase(z),
        "unit_direction": None if magnitude == 0 else z / magnitude
    }

for z in [3 + 4j, -1 + 1j, 0j]:
    print(z)
    print(analyze_complex(z))
    print()

(3+4j)
{'real': 3.0, 'imag': 4.0, 'conjugate': (3-4j), 'magnitude': 5.0, 'phase': 0.9272952180016122, 'unit_direction': (0.6+0.8j)}

(-1+1j)
{'real': -1.0, 'imag': 1.0, 'conjugate': (-1-1j), 'magnitude': 1.4142135623730951, 'phase': 2.356194490192345, 'unit_direction': (-0.7071067811865475+0.7071067811865475j)}

0j
{'real': 0.0, 'imag': 0.0, 'conjugate': -0j, 'magnitude': 0.0, 'phase': 0.0, 'unit_direction': None}



### Solution explanation

This problem combines several core complex-number operations: real and imaginary extraction, conjugation, magnitude, phase, and normalization. It also handles the special case where zero has no direction.